In [ ]:
#Classes in Python
class Employee:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def get_name(self):
    return self.name
  def get_age(self):
    return self.age
  def set_name(self, name):
    self.name = name
  def set_age(self, age):
    self.age = age
  def introduce(self):
    return f"my name is {self.name} and i am {self.age} years old"

In [ ]:
e = Employee("peter",25)

In [ ]:
e.introduce()

'my name is peter and i am 25 years old'

In [ ]:
e.get_name()

'peter'

In [ ]:
e.get_age()

25

In [ ]:
e.set_age(35)
e.get_age()

35

In [ ]:
e.introduce()

'my name is peter and i am 35 years old'

In [ ]:
!python file2.py 20 30

python3: can't open file '/content/file2.py': [Errno 2] No such file or directory


In [ ]:
!python file1.py

python3: can't open file '/content/file1.py': [Errno 2] No such file or directory


In [ ]:
import numpy as np

In [ ]:
#Scaler
a_scalar = np.array(10)
a_scalar

array(10)

In [ ]:
print(a_scalar.shape)

()


In [ ]:
print(a_scalar.ndim)

0


In [ ]:
#Vector
a_vector = np.array([1,2,3,4,5])
print(a_vector)

[1 2 3 4 5]


In [ ]:
print(a_vector.shape)

(5,)


In [ ]:
print(a_vector.ndim)

1


In [ ]:
a_vector1 = np.arange(20)
print(a_vector1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
a_vector2 = np.array(range(10))
print(a_vector2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Matrix
a_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(a_matrix.shape)

(3, 3)


In [ ]:
#Matrix
a_tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(a_tensor)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
print(a_tensor.shape)

(2, 3, 3)


In [ ]:
print(a_tensor.ndim)

3


In [ ]:
print(a_vector)

[1 2 3 4 5]


In [ ]:
print(a_vector[0])

1


In [ ]:
print(a_vector[0:3])

[1 2 3]


In [ ]:
a_mat1 = np.arange(18).reshape(2,3,3)
print(a_mat1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [ ]:
ex1 = np.arange(1,21)

In [ ]:
print(ex1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
print(ex1[2:])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
print(ex1[::2])

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
print(ex1[::-1])

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
am = np.array([[10,15,16],[17,18,19],[1,15,25]])
print(am)

[[10 15 16]
 [17 18 19]
 [ 1 15 25]]


In [ ]:
print(am[1:3,1:3])

[[18 19]
 [15 25]]


In [ ]:
print(am[1:3,0:2])

[[17 18]
 [ 1 15]]
